Vlaicu getting locale
bitdefender/www-landing-pages pull request #408
Opened 2024-10-17 08:32 UTC by ltiseanu

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Documentation
- [ ] I have updated the sidekick documentation.
- [ ] I have updated new baselines in GhostInspector.

Test URLs:
- Before: https://main--www-landing-pages--bitdefender.hlx.page/drafts/test-page/
- After: https://<branch>--www-landing-pages--bitdefender.hlx.page/drafts/test-page/

2024-10-17 12:07 UTC, enake requested changes

2024-10-17 12:07 UTC, enake commented on _src-lp/scripts/vendor/product.js
> +      const fetchLocale = `https://www.bitdefender.com/p-api/v1/countries/${country.toUpperCase()}/locales`;
Muta constanta la inceput de fisier. All caps.

2024-10-17 12:07 UTC, enake commented on _src-lp/scripts/vendor/product.js
> +      fetch(fetchLocale).then(response => {
Ai nevoie sa await dupa acel fetch.

2024-10-17 12:07 UTC, enake commented on _src-lp/scripts/vendor/product.js
> +        locale = data[0].locale;
locale nu va avea nicio valoare

2024-10-17 21:42 UTC, ltiseanu commented on _src-lp/scripts/vendor/product.js
> +      const fetchLocale = `https://www.bitdefender.com/p-api/v1/countries/${country.toUpperCase()}/locales`;
done

2024-10-17 21:42 UTC, ltiseanu commented on _src-lp/scripts/vendor/product.js
> +      fetch(fetchLocale).then(response => {
done

2024-10-17 21:43 UTC, ltiseanu commented on _src-lp/scripts/vendor/product.js
> +        locale = data[0].locale;
done

2024-10-21 06:58 UTC, enake approved these changes

2024-10-21 12:40 UTC, inastase approved these changes

2024-10-21 13:45 UTC, merged